### ISSUE TITLE
Application stop working

### ISSUE THREAD

**Issue by marchrius** [oplik0/solo2-desktop#56]
OS: Pos_OS (Ubuntu 22.04 based)

I receive this error when try to start application from terminal / gui

`RUST_BACKTRACE=full solo2-desktop`
```
thread 'main' panicked at 'data.len() must fit the width, height, and row_stride', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gdk-pixbuf-0.15.11/src/pixbuf.rs:52:13
stack backtrace:
   0:     0x55ff0b464f61 - std::backtrace_rs::backtrace::libunwind::trace::he648b5c8dd376705
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ff0b464f61 - std::backtrace_rs::backtrace::trace_unsynchronized::h5da3e203eef39e9f
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ff0b464f61 - std::sys_common::backtrace::_print_fmt::h8d28d3f20588ae4c
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55ff0b464f61 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd9a5b0c9c6b058c0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55ff0b493fdf - core::fmt::rt::Argument::fmt::h0afc04119f252b53
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
   5:     0x55ff0b493fdf - core::fmt::write::h50b1b3e73851a6fe
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
   6:     0x55ff0b460a57 - std::io::Write::write_fmt::h184eaf275e4484f0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/io/mod.rs:1714:15
   7:     0x55ff0b464d75 - std::sys_common::backtrace::_print::hf58c3a5a25090e71
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55ff0b464d75 - std::sys_common::backtrace::print::hb9cf0a7c7f077819
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55ff0b4662a3 - std::panicking::default_hook::{{closure}}::h066adb2e3f3e2c07
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:269:22
  10:     0x55ff0b466034 - std::panicking::default_hook::h277fa2776900ff14
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:288:9
  11:     0x55ff0b466829 - std::panicking::rust_panic_with_hook::hceaf38da6d9db792
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:705:13
  12:     0x55ff0b4666e1 - std::panicking::begin_panic_handler::{{closure}}::h2bce3ed2516af7df
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:595:13
  13:     0x55ff0b4653c6 - std::sys_common::backtrace::__rust_end_short_backtrace::h090f3faf8f98a395
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55ff0b466472 - rust_begin_unwind
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
  15:     0x55ff0af1bc23 - core::panicking::panic_fmt::h4ec8274704d163a3
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
  16:     0x55ff0b2c9add - tao::platform_impl::platform::icon::<impl core::convert::From<tao::platform_impl::platform::icon::PlatformIcon> for gdk_pixbuf::auto::pixbuf::Pixbuf>::from::hbfc23e0bedbe901f
  17:     0x55ff0b060912 - tao::platform_impl::platform::window::Window::new::h14369d68effde549
  18:     0x55ff0afe0fa3 - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::create_window::h3cfd613dc48e7117
  19:     0x55ff0b0726fb - tauri::app::Builder<R>::run::h7eeef3f01adf8430
  20:     0x55ff0b00516b - solo2_desktop::main::hf3cb7a51e5322212
  21:     0x55ff0b03abd3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h81541935c3bbd776
  22:     0x55ff0af532c9 - std::rt::lang_start::{{closure}}::h8c200028f757c408
  23:     0x55ff0b45b59b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h75ba4244a1c7bb54
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:284:13
  24:     0x55ff0b45b59b - std::panicking::try::do_call::h0a2baa36dea975a1
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  25:     0x55ff0b45b59b - std::panicking::try::h0e42aa233d4224d4
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  26:     0x55ff0b45b59b - std::panic::catch_unwind::hefdfd8f482606434
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  27:     0x55ff0b45b59b - std::rt::lang_start_internal::{{closure}}::h457959f0f91da23b
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:48
  28:     0x55ff0b45b59b - std::panicking::try::do_call::h112cfd1acb38183b
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  29:     0x55ff0b45b59b - std::panicking::try::ha64f15b20cec18ca
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  30:     0x55ff0b45b59b - std::panic::catch_unwind::hbacc2b68ee2c119e
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  31:     0x55ff0b45b59b - std::rt::lang_start_internal::h5f408694586c2a05
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:20
  32:     0x55ff0b006355 - main
  33:     0x7f7fd1c29d90 - <unknown>
  34:     0x7f7fd1c29e40 - __libc_start_main
  35:     0x55ff0af1c525 - _start
  36:                0x0 - <unknown>
```

**Comment by oplik0** [comment]
Can you try [v1.0.0](https://github.com/oplik0/solo2-desktop/releases/tag/solo2-desktop-v1.0.0) (note: I'm doing away with the `alpha` markings since it's annoying for CI, there weren't any significant changes other than updates)?

I regenerated the icon (and updated Tauri), but I don't have time right now to test on Ubuntu unfortunately, so I don't know it really fixed the issue.
